### ISSUE TITLE
How to test a dummy variable as a moderator in a full SEM model (within lavaan)

### ISSUE THREAD

**Issue by amielaugustin** [Kss2k/modsem#3]
Hello everyone ! I would like to ask a few questions. 

I need to run a full SEM where latent Y is should be predicted by latent X and latent Z. X and Z are allowed to correlate.
The six indicators related to the variable Y are coming from a merge of data between two different scales/questionnary (each participant responded to only one of the two versions). So if we can assign V and W as the latent variables representing the two old versions of the questionnary coming from the pre-merged columns for each indicator, approximatively half the population responded to V and the other part responded to W.

In the dataset, we have a group dummy variable that mentions which old version (V or W, assigning at 0 or 1) participants have responded.

The main goal of the analysis is to test if we can ask in two different ways (so with two different questionnaries) what we think is supposed to be the same construct, so it's why we have merged the two different versions in order to have one. But of course, we want to test whether the original versions could act as a moderator in the relationship between X and Y or Z and Y, if there is an original effect of X (or Z) on Y.

How should I proceed exactly to test this moderation effect ? Should I run a multigroup SEM analysis even if the participants responded to a different version of the construct ? And even if I want to test in the same model the effect of X on Y within the all population ? 
I'm note sure if I can use my dummy variable and in what extent. I'm a bit stuck with this so any kind answers are welcome !
Thanks a lot for reading,
Best,
Augustin

**Comment by Kss2k** [comment]
If I have understood you correctly the moderator in this case should be the dummy variable indicating what questionnaire the values were gathered from. While you can do interactions between latent and observed variables in modsem (see https://bookdown.org/slupphaugkjell/quartomodsem/intro.html), it sounds as though you should use a multi group model in this case, since you have a categorical moderator, which potentially moderates both X and Z

You can check out this:
https://web.pdx.edu/~newsomj/semclass/ho_moderation.pdf 

There is a section on moderation between latent and categorical variables there.

Best,
Kjell

**Comment by amielaugustin** [comment]
Thanks a lot for your response ! So according to you, I should do this even if I'm interested in accounting for the effect of the all population between X and Y ? 
It's why I'm a bit confused, the fact that the supposed moderator should/could be treated as a multigroup model but that the hypothesis on the relationship between the X factor (IV) and Y should account for the all population (not dividing the groups).

**Comment by Kss2k** [comment]
I see,

If I understand you correctly, using a single group model with an interaction term (using modsem, and `method = "pind"`) wouldn't change your problem. Your coefficient (simple effects) for X and Z would in that case not represent the effect of X and Z,  but for the reference group (dummy = 0). 

It kind of depends, but you might want to run two models, one multi group. And one single group. In the single group you can estimate the effects for X and Z for the whole population, and in the multi group you can pick out the effects in each population. You would of course have to be careful in interpreting the single group model, if there is a significant (and depending on the effect size) interaction effects -- since it would indicate that your constructs might not measure the same construct.
